services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./data_pgadmin:/var/lib/pgadmin:rw"
      - "./config_local.py:/pgadmin4/config_local.py:ro"
    ports:
      - "8080:80"
    user: "5050:5050"
    depends_on:
      - pgdatabase
    init: true

  pgadmin_init:
    image: busybox
    command: sh -c "mkdir -p /var/lib/pgadmin/sessions && chown -R 5050:5050 /var/lib/pgadmin"
    volumes:
      - "./data_pgadmin:/var/lib/pgadmin:rw"
    user: "root"